# Generated by Django 3.1.2 on 2021-03-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.IntegerField(primary_key=True, serialize=False)),
                ('name_car', models.CharField(max_length=50)),
                ('type_car', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('kilometrage', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='Cpb',
            fields=[
                ('id_cpb', models.IntegerField(primary_key=True, serialize=False)),
                ('puissance', models.CharField(max_length=50)),
                ('boite_a_vitesse', models.CharField(max_length=50)),
                ('carburant', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cpb',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id_model', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id_price', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=50)),
                ('annee', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='VoitureModel',
            fields=[
                ('id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('name_car', models.CharField(default=False, max_length=50)),
                ('type_car', models.CharField(default=False, max_length=50)),
                ('price', models.IntegerField()),
                ('ville', models.CharField(default=False, max_length=50)),
                ('day', models.CharField(default=False, max_length=50)),
                ('carburant', models.CharField(default=False, max_length=50)),
                ('puissance', models.IntegerField()),
                ('boite_a_vitesse', models.CharField(default=False, max_length=50)),
                ('kilometrage', models.CharField(default=False, max_length=50)),
                ('annee', models.IntegerField()),
                ('marque', models.CharField(default=False, max_length=50)),
                ('model', models.CharField(default=False, max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Fact_car',
            fields=[
                ('id_fact', models.IntegerField(primary_key=True, serialize=False)),
                ('id_car_fk', models.ForeignKey(db_column='id_car', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.car')),
                ('id_cpb_fk', models.ForeignKey(db_column='id_cpb', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cpb')),
                ('id_model_fk', models.ForeignKey(db_column='id_model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.model')),
                ('id_price_fk', models.ForeignKey(db_column='id_price', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.price')),
            ],
            options={
                'db_table': 'fact_car',
            },
        ),
    ]
