# Generated by Django 3.1.6 on 2021-02-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureModel',
            fields=[
                ('id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('name_car', models.CharField(default=False, max_length=50)),
                ('type_car', models.CharField(default=False, max_length=50)),
                ('price', models.CharField(default=False, max_length=50)),
                ('ville', models.CharField(default=False, max_length=50)),
                ('carburant', models.CharField(default=False, max_length=50)),
                ('puissance', models.IntegerField()),
                ('boite_a_vitesse', models.CharField(default=False, max_length=50)),
                ('kilometrage', models.CharField(default=False, max_length=50)),
                ('annee', models.IntegerField()),
                ('marque', models.CharField(default=False, max_length=50)),
                ('model', models.CharField(default=False, max_length=50)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
