# Generated by Django 3.1.2 on 2021-02-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210210_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='voituremodel',
            name='time',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
