# Generated by Django 3.1.2 on 2021-02-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_voituremodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='voituremodel',
            name='descriptions',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
