# Generated by Django 3.1.2 on 2021-02-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_voituremodel_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voituremodel',
            name='descriptions',
            field=models.TextField(),
        ),
    ]
