# Generated by Django 3.1.2 on 2021-02-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210225_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voituremodel',
            old_name='descriptions',
            new_name='description',
        ),
    ]
